cc_library(
    name = "naki3d-protobuf",
    srcs = [
        "cec.pb.cc",
        "discovery.pb.cc",
        "emt-grpc.pb.cc",
        "sensors.pb.cc",
        "types.pb.cc",
    ],
    hdrs = [
        "cec.pb.h",
        "discovery.pb.h",
        "emt-grpc.pb.h",
        "sensors.pb.h",
        "types.pb.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
    ],
    alwayslink = 1,
)
