// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handtracking.proto

#include "handtracking.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace naki3d {
namespace common {
namespace protocol {
}  // namespace protocol
}  // namespace common
}  // namespace naki3d
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_handtracking_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_handtracking_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_handtracking_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_handtracking_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_handtracking_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022handtracking.proto\022\026naki3d.common.prot"
  "ocol*\262\001\n\017HandGestureType\022\026\n\022GESTURE_SWIP"
  "E_LEFT\020\000\022\027\n\023GESTURE_SWIPE_RIGHT\020\001\022\024\n\020GES"
  "TURE_SWIPE_UP\020\002\022\026\n\022GESTURE_SWIPE_DOWN\020\003\022"
  "\026\n\022GESTURE_CLOSE_HAND\020\004\022\025\n\021GESTURE_OPEN_"
  "HAND\020\005\022\021\n\rGESTURE_PINCH\020\006*\037\n\010HandSide\022\010\n"
  "\004LEFT\020\000\022\t\n\005RIGHT\020\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_handtracking_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_handtracking_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_handtracking_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_handtracking_2eproto = {
  false, false, descriptor_table_protodef_handtracking_2eproto, "handtracking.proto", 266,
  &descriptor_table_handtracking_2eproto_once, descriptor_table_handtracking_2eproto_sccs, descriptor_table_handtracking_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_handtracking_2eproto::offsets,
  file_level_metadata_handtracking_2eproto, 0, file_level_enum_descriptors_handtracking_2eproto, file_level_service_descriptors_handtracking_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_handtracking_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_handtracking_2eproto)), true);
namespace naki3d {
namespace common {
namespace protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HandGestureType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_handtracking_2eproto);
  return file_level_enum_descriptors_handtracking_2eproto[0];
}
bool HandGestureType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HandSide_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_handtracking_2eproto);
  return file_level_enum_descriptors_handtracking_2eproto[1];
}
bool HandSide_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace common
}  // namespace naki3d
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
