// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: keyboard.proto

#include "keyboard.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace naki3d {
namespace common {
namespace protocol {
class KeyboardUpdateDataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<KeyboardUpdateData> _instance;
} _KeyboardUpdateData_default_instance_;
}  // namespace protocol
}  // namespace common
}  // namespace naki3d
static void InitDefaultsscc_info_KeyboardUpdateData_keyboard_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::naki3d::common::protocol::_KeyboardUpdateData_default_instance_;
    new (ptr) ::naki3d::common::protocol::KeyboardUpdateData();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::naki3d::common::protocol::KeyboardUpdateData::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_KeyboardUpdateData_keyboard_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_KeyboardUpdateData_keyboard_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_keyboard_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_keyboard_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_keyboard_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_keyboard_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::naki3d::common::protocol::KeyboardUpdateData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::naki3d::common::protocol::KeyboardUpdateData, type_),
  PROTOBUF_FIELD_OFFSET(::naki3d::common::protocol::KeyboardUpdateData, keycode_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::naki3d::common::protocol::KeyboardUpdateData)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::naki3d::common::protocol::_KeyboardUpdateData_default_instance_),
};

const char descriptor_table_protodef_keyboard_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016keyboard.proto\022\026naki3d.common.protocol"
  "\"Z\n\022KeyboardUpdateData\0223\n\004type\030\001 \001(\0162%.n"
  "aki3d.common.protocol.KeyActionType\022\017\n\007k"
  "eycode\030\002 \001(\005*)\n\rKeyActionType\022\n\n\006KEY_UP\020"
  "\000\022\014\n\010KEY_DOWN\020\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_keyboard_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_keyboard_2eproto_sccs[1] = {
  &scc_info_KeyboardUpdateData_keyboard_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_keyboard_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_keyboard_2eproto = {
  false, false, descriptor_table_protodef_keyboard_2eproto, "keyboard.proto", 183,
  &descriptor_table_keyboard_2eproto_once, descriptor_table_keyboard_2eproto_sccs, descriptor_table_keyboard_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_keyboard_2eproto::offsets,
  file_level_metadata_keyboard_2eproto, 1, file_level_enum_descriptors_keyboard_2eproto, file_level_service_descriptors_keyboard_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_keyboard_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_keyboard_2eproto)), true);
namespace naki3d {
namespace common {
namespace protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* KeyActionType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_keyboard_2eproto);
  return file_level_enum_descriptors_keyboard_2eproto[0];
}
bool KeyActionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void KeyboardUpdateData::InitAsDefaultInstance() {
}
class KeyboardUpdateData::_Internal {
 public:
};

KeyboardUpdateData::KeyboardUpdateData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:naki3d.common.protocol.KeyboardUpdateData)
}
KeyboardUpdateData::KeyboardUpdateData(const KeyboardUpdateData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&keycode_) -
    reinterpret_cast<char*>(&type_)) + sizeof(keycode_));
  // @@protoc_insertion_point(copy_constructor:naki3d.common.protocol.KeyboardUpdateData)
}

void KeyboardUpdateData::SharedCtor() {
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&keycode_) -
      reinterpret_cast<char*>(&type_)) + sizeof(keycode_));
}

KeyboardUpdateData::~KeyboardUpdateData() {
  // @@protoc_insertion_point(destructor:naki3d.common.protocol.KeyboardUpdateData)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void KeyboardUpdateData::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void KeyboardUpdateData::ArenaDtor(void* object) {
  KeyboardUpdateData* _this = reinterpret_cast< KeyboardUpdateData* >(object);
  (void)_this;
}
void KeyboardUpdateData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void KeyboardUpdateData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const KeyboardUpdateData& KeyboardUpdateData::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_KeyboardUpdateData_keyboard_2eproto.base);
  return *internal_default_instance();
}


void KeyboardUpdateData::Clear() {
// @@protoc_insertion_point(message_clear_start:naki3d.common.protocol.KeyboardUpdateData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&keycode_) -
      reinterpret_cast<char*>(&type_)) + sizeof(keycode_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KeyboardUpdateData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .naki3d.common.protocol.KeyActionType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::naki3d::common::protocol::KeyActionType>(val));
        } else goto handle_unusual;
        continue;
      // int32 keycode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          keycode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* KeyboardUpdateData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:naki3d.common.protocol.KeyboardUpdateData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .naki3d.common.protocol.KeyActionType type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // int32 keycode = 2;
  if (this->keycode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_keycode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:naki3d.common.protocol.KeyboardUpdateData)
  return target;
}

size_t KeyboardUpdateData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:naki3d.common.protocol.KeyboardUpdateData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .naki3d.common.protocol.KeyActionType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  // int32 keycode = 2;
  if (this->keycode() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_keycode());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KeyboardUpdateData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:naki3d.common.protocol.KeyboardUpdateData)
  GOOGLE_DCHECK_NE(&from, this);
  const KeyboardUpdateData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<KeyboardUpdateData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:naki3d.common.protocol.KeyboardUpdateData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:naki3d.common.protocol.KeyboardUpdateData)
    MergeFrom(*source);
  }
}

void KeyboardUpdateData::MergeFrom(const KeyboardUpdateData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:naki3d.common.protocol.KeyboardUpdateData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.keycode() != 0) {
    _internal_set_keycode(from._internal_keycode());
  }
}

void KeyboardUpdateData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:naki3d.common.protocol.KeyboardUpdateData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyboardUpdateData::CopyFrom(const KeyboardUpdateData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:naki3d.common.protocol.KeyboardUpdateData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyboardUpdateData::IsInitialized() const {
  return true;
}

void KeyboardUpdateData::InternalSwap(KeyboardUpdateData* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(KeyboardUpdateData, keycode_)
      + sizeof(KeyboardUpdateData::keycode_)
      - PROTOBUF_FIELD_OFFSET(KeyboardUpdateData, type_)>(
          reinterpret_cast<char*>(&type_),
          reinterpret_cast<char*>(&other->type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata KeyboardUpdateData::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace common
}  // namespace naki3d
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::naki3d::common::protocol::KeyboardUpdateData* Arena::CreateMaybeMessage< ::naki3d::common::protocol::KeyboardUpdateData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::naki3d::common::protocol::KeyboardUpdateData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
